version: "2"

services:
  payments:
    image: payments:0.1
    container_name: payments_app
    command: "sbt run"
    ports:
      - 8080:8080
    networks:
      - front
    depends_on:
      - db
  db:
    image: postgres:13.2
    container_name: psql
    env_file:
      - database.env
    volumes:
      - postgres-database:/var/lib/postgresql/data
    networks:
      - front
volumes:
  postgres-database:
networks:
  front:

