version: "2"

services:
  db:
    image: postgres:13
    container_name: psql
    env_file:
      - database.env
    volumes:
      - postgres-database:/var/lib/postgresql/data
    ports:
      - 5999:5432
    networks:
      - front
volumes:
  postgres-database:
networks:
  front:

