version: "2"

services:
  payments:
    image: base_scala:latest
    user: 1000:1000
    command: ["-l", "-c", "sbt ~reStart & cd src/main/client/expenses && npm install && npm start"]
    environment: 
      - JAVA_OPTS=-Xms512m -Xmx1024m -Xss1M
    volumes: 
      - ../.ivy2:/home/dev/.ivy2
      - ../.cache:/home/dev/.cache
      - ~/.npmrc:/home/dev/.npmrc
      - ../:/usr/src/app
    ports: 
      - "3000:3000"
    networks: 
      - front
    depends_on: 
      - db
  db:
    image: postgres:13
    container_name: psql
    env_file:
      - database.env
    volumes:
      - postgres-database:/var/lib/postgresql/data
    ports:
      - 5999:5432
    networks:
      - front
volumes:
  postgres-database:
networks:
  front:

